[package]
name = "luce_ai"
source = "src"

[dependencies]
luce_config = "../luce-config"
luce_http_client = "../luce-http-client"

[exports]
config = "luce_ai.config"
openrouter = "luce_ai.openrouter"
ai_task = "luce_ai.task"
